/* ===============================================================
Copyright 2026, Infineon Technologies AG or an 
affiliate of Infineon Technologies AG.  All rights reserved.
 
This software, associated documentation and materials ("Software") is owned by
Infineon Technologies AG or one of its affiliates ("Infineon") and is 
protected by and subject to worldwide patent protection (United States and 
foreign), United States copyright laws and international treaty provisions. 
Therefore, you may use this Software only as provided in the license agreement
accompanying the software package from which you obtained this 
Software ("EULA"). If no EULA applies, then any reproduction, modification, 
translation, compilation, or representation of this Software is prohibited 
without the express written permission of Infineon.
 
Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF 
ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
NONINFRINGEMENT, IMPLIED WARRANTIES OF  MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE.  Infineon reserves the right to make
changes to the Software without notice. Infineon does not assume any liability
arising out of the application or use of the Software or any product or 
circuit described in the Software. Infineon does not authorize its products 
for use in any products where a malfunction or failure of the Infineon product 
may reasonably be expected to result in significant property damage, injury or
death ("High Risk Product").  By including Infineon 's product in a High Risk 
Product, the manufacturer of such system or application assumes all risk of 
such use and in doing so agrees to indemnify Infineon against all liability.

 ===============================================================
*/ 
// File : BrentKungAdder.v 
// Author : yangjun 
// Date : 20:12:04    02/03/2026 
// Revision :  
// =============================================================== 
// Description : 
/*
---- Auto Generated by MetaRTL , a MetaGen application
---- Contact: ParitoshKumar.Sinha@infineon.com
---- Contact: Yash.Ranjan@infineon.com
===============================================================
*/


module BrentKungAdder (
    input [7:0] A_vec_i,
    input [7:0] B_vec_i,
    output [7:0] S_vec_o,
    output C_out_o,
    input clk_i,
    input rst_i
);

wire   INDEX00_Outp_o_s;
wire   INDEX01_Outp_o_s;
wire   XOR_gate_00_Outp_o_s;
wire   INDEX02_Outp_o_s;
wire   INDEX03_Outp_o_s;
wire   AND_gate_00_Outp_o_s;
wire   INDEX04_Outp_o_s;
wire   INDEX05_Outp_o_s;
wire   XOR_gate_01_Outp_o_s;
wire   INDEX06_Outp_o_s;
wire   INDEX07_Outp_o_s;
wire   AND_gate_01_Outp_o_s;
wire   AND_gate_11_Outp_o_s;
wire   OR_gate_01_Outp_o_s;
wire   AND_gate_21_Outp_o_x;
wire   INDEX08_Outp_o_s;
wire   INDEX09_Outp_o_s;
wire   XOR_gate_02_Outp_o_s;
wire   INDEX10_Outp_o_s;
wire   INDEX11_Outp_o_s;
wire   AND_gate_02_Outp_o_s;
wire   INDEX12_Outp_o_s;
wire   INDEX13_Outp_o_s;
wire   XOR_gate_03_Outp_o_s;
wire   INDEX14_Outp_o_s;
wire   INDEX15_Outp_o_s;
wire   AND_gate_03_Outp_o_s;
wire   AND_gate_13_Outp_o_s;
wire   OR_gate_03_Outp_o_s;
wire   AND_gate_23_Outp_o_s;
wire   INDEX16_Outp_o_s;
wire   INDEX17_Outp_o_s;
wire   XOR_gate_04_Outp_o_s;
wire   INDEX18_Outp_o_s;
wire   INDEX19_Outp_o_s;
wire   AND_gate_04_Outp_o_s;
wire   INDEX20_Outp_o_s;
wire   INDEX21_Outp_o_s;
wire   XOR_gate_05_Outp_o_s;
wire   INDEX22_Outp_o_s;
wire   INDEX23_Outp_o_s;
wire   AND_gate_05_Outp_o_s;
wire   AND_gate_15_Outp_o_s;
wire   OR_gate_05_Outp_o_s;
wire   AND_gate_25_Outp_o_s;
wire   INDEX24_Outp_o_s;
wire   INDEX25_Outp_o_s;
wire   XOR_gate_06_Outp_o_s;
wire   INDEX26_Outp_o_s;
wire   INDEX27_Outp_o_s;
wire   AND_gate_06_Outp_o_s;
wire   INDEX28_Outp_o_s;
wire   INDEX29_Outp_o_s;
wire   XOR_gate_07_Outp_o_s;
wire   INDEX30_Outp_o_s;
wire   INDEX31_Outp_o_s;
wire   AND_gate_07_Outp_o_s;
wire   AND_gate_17_Outp_o_s;
wire   OR_gate_07_Outp_o_s;
wire   AND_gate_27_Outp_o_s;
wire   AND_gate_323_Outp_o_s;
wire   OR_gate_123_Outp_o_s;
wire   AND_gate_327_Outp_o_s;
wire   OR_gate_127_Outp_o_s;
wire   AND_gate_427_Outp_o_s;
wire   AND_gate_337_Outp_o_s;
wire   OR_gate_137_Outp_o_x;
wire   AND_gate_545_Outp_o_s;
wire   OR_gate_245_Outp_o_s;
wire   AND_gate_552_Outp_o_s;
wire   OR_gate_252_Outp_o_s;
wire   AND_gate_554_Outp_o_s;
wire   OR_gate_254_Outp_o_s;
wire   AND_gate_556_Outp_o_s;
wire   OR_gate_256_Outp_o_s;
wire   XOR_gate_21_Outp_o_s;
wire   XOR_gate_22_Outp_o_s;
wire   XOR_gate_23_Outp_o_s;
wire   XOR_gate_24_Outp_o_s;
wire   XOR_gate_25_Outp_o_s;
wire   XOR_gate_26_Outp_o_s;
wire   XOR_gate_27_Outp_o_s;
wire   AND_gate_7_Outp_o_s;

BrentKungAdder_INDEX00 comp_INDEX00(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX00_Outp_o_s )
);

BrentKungAdder_INDEX01 comp_INDEX01(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX01_Outp_o_s )
);

BrentKungAdder_XOR_gate_00 comp_XOR_gate_00(
    .In00_i ( INDEX00_Outp_o_s     ),
    .In01_i ( INDEX01_Outp_o_s     ),
    .Outp_o ( XOR_gate_00_Outp_o_s )
);

BrentKungAdder_INDEX02 comp_INDEX02(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX02_Outp_o_s )
);

BrentKungAdder_INDEX03 comp_INDEX03(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX03_Outp_o_s )
);

BrentKungAdder_AND_gate_00 comp_AND_gate_00(
    .In00_i ( INDEX02_Outp_o_s     ),
    .In01_i ( INDEX03_Outp_o_s     ),
    .Outp_o ( AND_gate_00_Outp_o_s )
);

BrentKungAdder_INDEX04 comp_INDEX04(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX04_Outp_o_s )
);

BrentKungAdder_INDEX05 comp_INDEX05(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX05_Outp_o_s )
);

BrentKungAdder_XOR_gate_01 comp_XOR_gate_01(
    .In00_i ( INDEX04_Outp_o_s     ),
    .In01_i ( INDEX05_Outp_o_s     ),
    .Outp_o ( XOR_gate_01_Outp_o_s )
);

BrentKungAdder_INDEX06 comp_INDEX06(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX06_Outp_o_s )
);

BrentKungAdder_INDEX07 comp_INDEX07(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX07_Outp_o_s )
);

BrentKungAdder_AND_gate_01 comp_AND_gate_01(
    .In00_i ( INDEX06_Outp_o_s     ),
    .In01_i ( INDEX07_Outp_o_s     ),
    .Outp_o ( AND_gate_01_Outp_o_s )
);

BrentKungAdder_AND_gate_11 comp_AND_gate_11(
    .In00_i ( XOR_gate_01_Outp_o_s ),
    .In01_i ( AND_gate_00_Outp_o_s ),
    .Outp_o ( AND_gate_11_Outp_o_s )
);

BrentKungAdder_OR_gate_01 comp_OR_gate_01(
    .In00_i ( AND_gate_11_Outp_o_s ),
    .In01_i ( AND_gate_01_Outp_o_s ),
    .Outp_o ( OR_gate_01_Outp_o_s  )
);

BrentKungAdder_AND_gate_21 comp_AND_gate_21(
    .In00_i ( XOR_gate_01_Outp_o_s ),
    .In01_i ( XOR_gate_00_Outp_o_s )
);

BrentKungAdder_INDEX08 comp_INDEX08(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX08_Outp_o_s )
);

BrentKungAdder_INDEX09 comp_INDEX09(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX09_Outp_o_s )
);

BrentKungAdder_XOR_gate_02 comp_XOR_gate_02(
    .In00_i ( INDEX08_Outp_o_s     ),
    .In01_i ( INDEX09_Outp_o_s     ),
    .Outp_o ( XOR_gate_02_Outp_o_s )
);

BrentKungAdder_INDEX10 comp_INDEX10(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX10_Outp_o_s )
);

BrentKungAdder_INDEX11 comp_INDEX11(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX11_Outp_o_s )
);

BrentKungAdder_AND_gate_02 comp_AND_gate_02(
    .In00_i ( INDEX10_Outp_o_s     ),
    .In01_i ( INDEX11_Outp_o_s     ),
    .Outp_o ( AND_gate_02_Outp_o_s )
);

BrentKungAdder_INDEX12 comp_INDEX12(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX12_Outp_o_s )
);

BrentKungAdder_INDEX13 comp_INDEX13(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX13_Outp_o_s )
);

BrentKungAdder_XOR_gate_03 comp_XOR_gate_03(
    .In00_i ( INDEX12_Outp_o_s     ),
    .In01_i ( INDEX13_Outp_o_s     ),
    .Outp_o ( XOR_gate_03_Outp_o_s )
);

BrentKungAdder_INDEX14 comp_INDEX14(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX14_Outp_o_s )
);

BrentKungAdder_INDEX15 comp_INDEX15(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX15_Outp_o_s )
);

BrentKungAdder_AND_gate_03 comp_AND_gate_03(
    .In00_i ( INDEX14_Outp_o_s     ),
    .In01_i ( INDEX15_Outp_o_s     ),
    .Outp_o ( AND_gate_03_Outp_o_s )
);

BrentKungAdder_AND_gate_13 comp_AND_gate_13(
    .In00_i ( XOR_gate_03_Outp_o_s ),
    .In01_i ( AND_gate_02_Outp_o_s ),
    .Outp_o ( AND_gate_13_Outp_o_s )
);

BrentKungAdder_OR_gate_03 comp_OR_gate_03(
    .In00_i ( AND_gate_13_Outp_o_s ),
    .In01_i ( AND_gate_03_Outp_o_s ),
    .Outp_o ( OR_gate_03_Outp_o_s  )
);

BrentKungAdder_AND_gate_23 comp_AND_gate_23(
    .In00_i ( XOR_gate_03_Outp_o_s ),
    .In01_i ( XOR_gate_02_Outp_o_s ),
    .Outp_o ( AND_gate_23_Outp_o_s )
);

BrentKungAdder_INDEX16 comp_INDEX16(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX16_Outp_o_s )
);

BrentKungAdder_INDEX17 comp_INDEX17(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX17_Outp_o_s )
);

BrentKungAdder_XOR_gate_04 comp_XOR_gate_04(
    .In00_i ( INDEX16_Outp_o_s     ),
    .In01_i ( INDEX17_Outp_o_s     ),
    .Outp_o ( XOR_gate_04_Outp_o_s )
);

BrentKungAdder_INDEX18 comp_INDEX18(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX18_Outp_o_s )
);

BrentKungAdder_INDEX19 comp_INDEX19(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX19_Outp_o_s )
);

BrentKungAdder_AND_gate_04 comp_AND_gate_04(
    .In00_i ( INDEX18_Outp_o_s     ),
    .In01_i ( INDEX19_Outp_o_s     ),
    .Outp_o ( AND_gate_04_Outp_o_s )
);

BrentKungAdder_INDEX20 comp_INDEX20(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX20_Outp_o_s )
);

BrentKungAdder_INDEX21 comp_INDEX21(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX21_Outp_o_s )
);

BrentKungAdder_XOR_gate_05 comp_XOR_gate_05(
    .In00_i ( INDEX20_Outp_o_s     ),
    .In01_i ( INDEX21_Outp_o_s     ),
    .Outp_o ( XOR_gate_05_Outp_o_s )
);

BrentKungAdder_INDEX22 comp_INDEX22(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX22_Outp_o_s )
);

BrentKungAdder_INDEX23 comp_INDEX23(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX23_Outp_o_s )
);

BrentKungAdder_AND_gate_05 comp_AND_gate_05(
    .In00_i ( INDEX22_Outp_o_s     ),
    .In01_i ( INDEX23_Outp_o_s     ),
    .Outp_o ( AND_gate_05_Outp_o_s )
);

BrentKungAdder_AND_gate_15 comp_AND_gate_15(
    .In00_i ( XOR_gate_05_Outp_o_s ),
    .In01_i ( AND_gate_04_Outp_o_s ),
    .Outp_o ( AND_gate_15_Outp_o_s )
);

BrentKungAdder_OR_gate_05 comp_OR_gate_05(
    .In00_i ( AND_gate_15_Outp_o_s ),
    .In01_i ( AND_gate_05_Outp_o_s ),
    .Outp_o ( OR_gate_05_Outp_o_s  )
);

BrentKungAdder_AND_gate_25 comp_AND_gate_25(
    .In00_i ( XOR_gate_05_Outp_o_s ),
    .In01_i ( XOR_gate_04_Outp_o_s ),
    .Outp_o ( AND_gate_25_Outp_o_s )
);

BrentKungAdder_INDEX24 comp_INDEX24(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX24_Outp_o_s )
);

BrentKungAdder_INDEX25 comp_INDEX25(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX25_Outp_o_s )
);

BrentKungAdder_XOR_gate_06 comp_XOR_gate_06(
    .In00_i ( INDEX24_Outp_o_s     ),
    .In01_i ( INDEX25_Outp_o_s     ),
    .Outp_o ( XOR_gate_06_Outp_o_s )
);

BrentKungAdder_INDEX26 comp_INDEX26(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX26_Outp_o_s )
);

BrentKungAdder_INDEX27 comp_INDEX27(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX27_Outp_o_s )
);

BrentKungAdder_AND_gate_06 comp_AND_gate_06(
    .In00_i ( INDEX26_Outp_o_s     ),
    .In01_i ( INDEX27_Outp_o_s     ),
    .Outp_o ( AND_gate_06_Outp_o_s )
);

BrentKungAdder_INDEX28 comp_INDEX28(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX28_Outp_o_s )
);

BrentKungAdder_INDEX29 comp_INDEX29(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX29_Outp_o_s )
);

BrentKungAdder_XOR_gate_07 comp_XOR_gate_07(
    .In00_i ( INDEX28_Outp_o_s     ),
    .In01_i ( INDEX29_Outp_o_s     ),
    .Outp_o ( XOR_gate_07_Outp_o_s )
);

BrentKungAdder_INDEX30 comp_INDEX30(
    .In00_i ( A_vec_i          ),
    .Outp_o ( INDEX30_Outp_o_s )
);

BrentKungAdder_INDEX31 comp_INDEX31(
    .In00_i ( B_vec_i          ),
    .Outp_o ( INDEX31_Outp_o_s )
);

BrentKungAdder_AND_gate_07 comp_AND_gate_07(
    .In00_i ( INDEX30_Outp_o_s     ),
    .In01_i ( INDEX31_Outp_o_s     ),
    .Outp_o ( AND_gate_07_Outp_o_s )
);

BrentKungAdder_AND_gate_17 comp_AND_gate_17(
    .In00_i ( XOR_gate_07_Outp_o_s ),
    .In01_i ( AND_gate_06_Outp_o_s ),
    .Outp_o ( AND_gate_17_Outp_o_s )
);

BrentKungAdder_OR_gate_07 comp_OR_gate_07(
    .In00_i ( AND_gate_17_Outp_o_s ),
    .In01_i ( AND_gate_07_Outp_o_s ),
    .Outp_o ( OR_gate_07_Outp_o_s  )
);

BrentKungAdder_AND_gate_27 comp_AND_gate_27(
    .In00_i ( XOR_gate_07_Outp_o_s ),
    .In01_i ( XOR_gate_06_Outp_o_s ),
    .Outp_o ( AND_gate_27_Outp_o_s )
);

BrentKungAdder_AND_gate_323 comp_AND_gate_323(
    .In00_i ( AND_gate_23_Outp_o_s  ),
    .In01_i ( OR_gate_01_Outp_o_s   ),
    .Outp_o ( AND_gate_323_Outp_o_s )
);

BrentKungAdder_OR_gate_123 comp_OR_gate_123(
    .In00_i ( AND_gate_323_Outp_o_s ),
    .In01_i ( OR_gate_03_Outp_o_s   ),
    .Outp_o ( OR_gate_123_Outp_o_s  )
);

BrentKungAdder_AND_gate_327 comp_AND_gate_327(
    .In00_i ( AND_gate_27_Outp_o_s  ),
    .In01_i ( OR_gate_05_Outp_o_s   ),
    .Outp_o ( AND_gate_327_Outp_o_s )
);

BrentKungAdder_OR_gate_127 comp_OR_gate_127(
    .In00_i ( AND_gate_327_Outp_o_s ),
    .In01_i ( OR_gate_07_Outp_o_s   ),
    .Outp_o ( OR_gate_127_Outp_o_s  )
);

BrentKungAdder_AND_gate_427 comp_AND_gate_427(
    .In00_i ( AND_gate_27_Outp_o_s  ),
    .In01_i ( AND_gate_25_Outp_o_s  ),
    .Outp_o ( AND_gate_427_Outp_o_s )
);

BrentKungAdder_AND_gate_337 comp_AND_gate_337(
    .In00_i ( AND_gate_427_Outp_o_s ),
    .In01_i ( OR_gate_123_Outp_o_s  ),
    .Outp_o ( AND_gate_337_Outp_o_s )
);

BrentKungAdder_OR_gate_137 comp_OR_gate_137(
    .In00_i ( AND_gate_337_Outp_o_s ),
    .In01_i ( OR_gate_127_Outp_o_s  )
);

BrentKungAdder_AND_gate_545 comp_AND_gate_545(
    .In00_i ( AND_gate_25_Outp_o_s  ),
    .In01_i ( OR_gate_123_Outp_o_s  ),
    .Outp_o ( AND_gate_545_Outp_o_s )
);

BrentKungAdder_OR_gate_245 comp_OR_gate_245(
    .In00_i ( AND_gate_545_Outp_o_s ),
    .In01_i ( OR_gate_05_Outp_o_s   ),
    .Outp_o ( OR_gate_245_Outp_o_s  )
);

BrentKungAdder_AND_gate_552 comp_AND_gate_552(
    .In00_i ( XOR_gate_02_Outp_o_s  ),
    .In01_i ( OR_gate_01_Outp_o_s   ),
    .Outp_o ( AND_gate_552_Outp_o_s )
);

BrentKungAdder_OR_gate_252 comp_OR_gate_252(
    .In00_i ( AND_gate_552_Outp_o_s ),
    .In01_i ( AND_gate_02_Outp_o_s  ),
    .Outp_o ( OR_gate_252_Outp_o_s  )
);

BrentKungAdder_AND_gate_554 comp_AND_gate_554(
    .In00_i ( XOR_gate_04_Outp_o_s  ),
    .In01_i ( OR_gate_123_Outp_o_s  ),
    .Outp_o ( AND_gate_554_Outp_o_s )
);

BrentKungAdder_OR_gate_254 comp_OR_gate_254(
    .In00_i ( AND_gate_554_Outp_o_s ),
    .In01_i ( AND_gate_04_Outp_o_s  ),
    .Outp_o ( OR_gate_254_Outp_o_s  )
);

BrentKungAdder_AND_gate_556 comp_AND_gate_556(
    .In00_i ( XOR_gate_06_Outp_o_s  ),
    .In01_i ( OR_gate_245_Outp_o_s  ),
    .Outp_o ( AND_gate_556_Outp_o_s )
);

BrentKungAdder_OR_gate_256 comp_OR_gate_256(
    .In00_i ( AND_gate_556_Outp_o_s ),
    .In01_i ( AND_gate_06_Outp_o_s  ),
    .Outp_o ( OR_gate_256_Outp_o_s  )
);

BrentKungAdder_CONCAT comp_CONCAT(
    .Outp_o ( S_vec_o              ),
    .In00_i ( XOR_gate_27_Outp_o_s ),
    .In01_i ( XOR_gate_26_Outp_o_s ),
    .In02_i ( XOR_gate_25_Outp_o_s ),
    .In03_i ( XOR_gate_24_Outp_o_s ),
    .In04_i ( XOR_gate_23_Outp_o_s ),
    .In05_i ( XOR_gate_22_Outp_o_s ),
    .In06_i ( XOR_gate_21_Outp_o_s ),
    .In07_i ( XOR_gate_00_Outp_o_s )
);

BrentKungAdder_XOR_gate_21 comp_XOR_gate_21(
    .In00_i ( XOR_gate_01_Outp_o_s ),
    .In01_i ( AND_gate_00_Outp_o_s ),
    .Outp_o ( XOR_gate_21_Outp_o_s )
);

BrentKungAdder_XOR_gate_22 comp_XOR_gate_22(
    .In00_i ( XOR_gate_02_Outp_o_s ),
    .In01_i ( OR_gate_01_Outp_o_s  ),
    .Outp_o ( XOR_gate_22_Outp_o_s )
);

BrentKungAdder_XOR_gate_23 comp_XOR_gate_23(
    .In00_i ( XOR_gate_03_Outp_o_s ),
    .In01_i ( OR_gate_252_Outp_o_s ),
    .Outp_o ( XOR_gate_23_Outp_o_s )
);

BrentKungAdder_XOR_gate_24 comp_XOR_gate_24(
    .In00_i ( XOR_gate_04_Outp_o_s ),
    .In01_i ( OR_gate_123_Outp_o_s ),
    .Outp_o ( XOR_gate_24_Outp_o_s )
);

BrentKungAdder_XOR_gate_25 comp_XOR_gate_25(
    .In00_i ( XOR_gate_05_Outp_o_s ),
    .In01_i ( OR_gate_254_Outp_o_s ),
    .Outp_o ( XOR_gate_25_Outp_o_s )
);

BrentKungAdder_XOR_gate_26 comp_XOR_gate_26(
    .In00_i ( XOR_gate_06_Outp_o_s ),
    .In01_i ( OR_gate_245_Outp_o_s ),
    .Outp_o ( XOR_gate_26_Outp_o_s )
);

BrentKungAdder_XOR_gate_27 comp_XOR_gate_27(
    .In00_i ( XOR_gate_07_Outp_o_s ),
    .In01_i ( OR_gate_256_Outp_o_s ),
    .Outp_o ( XOR_gate_27_Outp_o_s )
);

BrentKungAdder_AND_gate_7 comp_AND_gate_7(
    .In00_i ( XOR_gate_07_Outp_o_s ),
    .In01_i ( OR_gate_256_Outp_o_s ),
    .Outp_o ( AND_gate_7_Outp_o_s  )
);

BrentKungAdder_OR_gate_3 comp_OR_gate_3(
    .In00_i ( AND_gate_7_Outp_o_s  ),
    .In01_i ( AND_gate_07_Outp_o_s ),
    .Outp_o ( C_out_o              )
);


endmodule

